# 1.首先，在workflow文件中定义触发器，例如每次推送到主分支时触发同步操作。
# 工作流名称
name: Sync Image to Aliyun  Example

env:
  # env_var: ${{ vars.ENV_CONTEXT_VAR }}
  DOCKERIMAGENAME: "breezedeus/cnocr-arm64:latest"
 
# 怎样触发工作流
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
 
# 2.添加一个job来执行同步操作。在workflow文件中，添加一个job 并指定使用的操作系统环境。
# 工作流程任务（通常含有一个或多个步骤）
jobs:
  build:
    runs-on: ubuntu-latest
 
    # 在job中添加步骤来执行同步操作。在上述job中，添加步骤来执行skopeo命令，从docker.io仓库拉取镜像，并将其推送到阿里云个人仓库。
    steps:
    - name: Git pull
      uses: actions/checkout@v3
 
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.9.1
    - name: Replace / with _
      id: replace
      run: |
        input_string="${{env.DOCKERIMAGENAME}}"
        replaced_string="${input_string//\//_}"
        echo "Replaced string: $replaced_string"
        echo "::set-output name=replaced::$replaced_string"

      
    # 设置项目Secrets以提供Docker Hub登录所需的用户名和密码。
    - name: Login to Docker Hub
      uses: docker/login-action@v2.2.0
      with:
        registry: registry.cn-hangzhou.aliyuncs.com
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
        logout: false
 
    # 使用shell命令批量同步所需的镜像到阿里云个人仓库中
    - name: Use Skopeo Tools Sync Image to Docker Hub
      run: |
        # 使用 skopeo 工具将镜像同步到阿里云个人仓库中，使用时请自行源和目标修改仓库名称和镜像名称
         skopeo copy docker://docker.io/${{env.DOCKERIMAGENAME}} docker://registry.cn-hangzhou.aliyuncs.com/codezm-sync/${{ steps.replace.outputs.replaced }}

    - name: Login to ghci Docker hub
      uses: docker/login-action@v2.2.0
      with:
        registry: ghcr.io
        username: ${{secrets.DOCKER_USERNAME_GITHUB}}
        password: ${{secrets.DOCKER_PASSWORD_GITHUB}}
        logout: false

    - name: Use Skopeo Tools Sync Image to Docker Hub
      run: |
        # 使用 skopeo 工具将镜像同步到阿里云个人仓库中，使用时请自行源和目标修改仓库名称和镜像名称
         skopeo copy docker://docker.io/${{env.DOCKERIMAGENAME}} docker://ghcr.io/codezm/${{ steps.replace.outputs.replaced }}

    - name: Set image visibility to public
      run: |
        echo "Changing visibility of the image to public..."
        STRING="${{steps.replace.outputs.replaced}}"
        OLD_IFS="$IFS"
        IFS=':'
        read -ra ADDR <<< "$STRING"
        IMAGE_NAME="ghcr.io/codezm/${ADDR[0]}"
        IMAGE_VERSION="${ADDR[1]}"
        IFS="$OLD_IFS"
        echo "https://api.github.com/user/packages/container/${IMAGE_NAME}/versions/${IMAGE_VERSION}"
        curl -X PATCH -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/vnd.github.v3+json" https://api.github.com/user/packages/container/${IMAGE_NAME}/versions/${IMAGE_VERSION} -d '{"visibility": "public"}'




